export const workExperience = [
  {
    company: 'Pacific Life',
    role: 'Cloud Engineer (Contract)',
    startDate: 'July 2026',
    endDate: 'Present',
    description: [
      'Building full-stack services for an enterprise transformation program in TypeScript, Node.js, and React, with AWS Lambda and CI/CD in Azure DevOps.',
      "Converted the program's stack from JavaScript to TypeScript, improving stability while continuing to hit new-feature demo deadlines.",
      'Took ownership of the v2 migration, maintaining uptime across both versions through a clean cutover, partnering with other teams to integrate the API with the web app, and identifying key performance bottlenecks.',
      'Built a code review automation workflow with GitHub Copilot CLI and PowerShell, standardizing review coverage across the team.',
    ],
    location: 'Newport Beach, CA',
    logo: '/images/logos/pacific-life-logo.png',
  },
  {
    company: 'Altametrics',
    role: 'Software Developer / Team Lead',
    startDate: 'January 2024',
    endDate: 'July 2026',
    description: [
      'Led an engineering team, hired and onboarded 2 engineers, and drove sprint planning and cross-functional coordination, shipping 13+ production applications across web, mobile, and backend.',
      'Architected React and Next.js front ends backed by NestJS APIs on AWS, serving thousands of daily users, including a restaurant association platform owned for 2.5 years across SSG, SSR, and client components.',
      'Built a RAG-powered content pipeline that processes industry data through LLM APIs and auto-publishes across multiple domains, driving 10,000+ weekly visitors.',
      'Shipped a React Native mobile app with OCR-powered data capture, reducing manual entry time by 40% for field teams.',
      'Automated CI/CD pipelines with GitHub Actions and Docker for seven white-labeled mobile apps, cutting build times by 90%.',
    ],
    location: 'Costa Mesa, CA',
    logo: '/images/logos/altametrics-logo.png',
  },
  {
    company: 'Freelance Developer',
    role: 'Software Engineer, Independent Contracts',
    startDate: 'June 2022',
    endDate: 'Present',
    description: [
      'Built huntingtonbeachtutoring.com end to end — design, development, SEO, and deployment on Vercel — for a local tutoring business.',
      'Rebuilt client WordPress sites in Next.js and TypeScript, improving page load speeds and growing organic traffic by 35%.',
      'Migrated client hosting to Vercel with automated CI/CD pipelines, eliminating recurring hosting costs.',
      'Took over a non-performant production application after prior developers stalled, restoring it to production quality through caching and image optimization, and contributed frontend features across its Next.js web and React Native iOS apps.',
    ],
    location: 'Remote',
    logo: '/images/logos/freelancer-logo.png',
  },
  {
    company: 'PL8CHAT',
    role: 'Full Stack Engineer',
    startDate: 'June 2023',
    endDate: 'June 2024',
    description: [
      'Built a real-time chat platform end to end with React Native, Node.js, and PostgreSQL, maintaining 99% uptime across iOS and Android.',
      'Designed a client-facing web dashboard for apartment management teams to monitor activity and manage residents.',
      'Reduced cloud hosting costs by 25% through database query optimization and server-side caching.',
    ],
    location: 'Remote',
    logo: '/images/logos/pl8chat-logo.png',
  },
  {
    company: 'edX (2U)',
    role: 'Teaching Assistant, Full Stack Web Development',
    startDate: 'May 2022',
    endDate: 'September 2024',
    description: [
      'Guided 100+ students through React, Node.js, and full-stack fundamentals, delivering live remote lessons, code reviews, and one-on-one support.',
      'Reviewed and debugged student projects, ensuring adherence to industry standards and best practices.',
      'Organized and conducted study sessions, increasing student success rates by 20%.',
    ],
    location: 'Remote',
    logo: '/images/logos/edx-logo.png',
  },
  {
    company: 'Shepard Bros',
    role: 'Research & Development Analytical Chemist',
    startDate: 'December 2020',
    endDate: 'December 2022',
    description: [
      'Formulated three new cleaning solutions to resolve customer issues with competing products, resulting in improved customer satisfaction and revenue.',
      'Tested products for quality control to ensure they met narrow chemical specifications, maintaining high standards of consistency and performance.',
    ],
    location: 'La Habra, CA',
    logo: '/images/logos/shepard-bros-logo.png',
  },
];
