export const workExperience = [
  {
    company: 'Altametrics',
    role: 'Web Developer',
    startDate: 'January 2024',
    endDate: 'Present',
    description: [
      'Built scalable applications using React, Next.js, Apollo GraphQL, and PostgreSQL.',
      'Revitalized a sales application, redeveloping it with Vue.js, TRPC, and PostgreSQL to meet team needs, transforming it into the exclusive tool for closing sales.',
      'Built an end-to-end automated content system for RestaurantAssociation.com using OOP and PostgreSQL to generate AI-driven articles, reducing content costs by 99%.',
      'Developed RestaurantAssociation.com from scratch, transforming it from a simple blog to an industry-leading platform using Next.js.',
      'Boosted Google Search ranking by 105% with SEO improvements and performance optimizations.',
      'Implemented CI/CD pipelines for mobile apps using Fastlane and Docker, streamlining deployments.',
    ],
    location: 'Costa Mesa, CA',
    logo: '/images/logos/altametrics-logo.png',
  },
  {
    company: 'PL8CHAT',
    role: 'Full Stack Software Engineer',
    startDate: 'August 2023',
    endDate: 'August 2024',
    description: [
      'Oversaw all technical design decisions, built the initial codebase, and successfully delivered the app to the App Store, enabling the CEO to secure investor interest.',
      'Architected and developed the initial codebase for a real-time chat app using React Native, ensuring seamless deployment on iOS and Android.',
      'Designed and implemented a secure PostgreSQL database with row-level security, improving data access speed by 30% and ensuring future scalability.',
      'Established a robust development environment with comprehensive documentation and automated scripts, reducing onboarding time for new developers by 50%.',
    ],
    location: 'Remote',
    logo: '/images/logos/pl8chat-logo.png',
  },
  {
    company: 'edX',
    role: 'Teaching Assistant',
    startDate: 'June 2021',
    endDate: 'December 2021',
    description: [
      'Provided technical mentorship to students in a full-stack web development bootcamp.',
      'Assisted students in understanding core concepts such as HTML, CSS, JavaScript, React, and Node.js.',
      'Reviewed and debugged student projects, ensuring adherence to industry standards and best practices.',
      'Organized and conducted study sessions, increasing student success rates by 20%.',
      'Supported instructors during live coding sessions and lectures.',
    ],
    location: 'Remote',
    logo: '/images/logos/edx-logo.png',
  },
  {
    company: 'Freelance Developer',
    role: 'Full-Stack Developer',
    startDate: 'June 2022',
    endDate: 'Present',
    description: [
      'Designed Shopify stores for e-commerce clients, including customized Liquid themes and seamless API integrations.',
      'Delivered React Native apps with a focus on modularity and multi-brand support.',
      'Developed scalable backend APIs using Node.js and PostgreSQL for various client projects.',
    ],
    location: 'Remote',
    logo: '/images/logos/freelancer-logo.png',
  },
  {
    company: 'Shepard Bros',
    role: 'Research & Development Analytical Chemist',
    startDate: 'December 2020',
    endDate: 'December 2022',
    description: [
      'Formulated three new cleaning solutions to resolve customer issues with competing products, resulting in improved customer satisfaction and revenue.',
      'Tested products for quality control to ensure they met narrow chemical specifications, maintaining high standards of consistency and performance.',
    ],
    location: 'La Habra, CA',
    logo: '/images/logos/shepard-bros-logo.png',
  },
];
